### ISSUE TITLE
NIC Improvements

### ISSUE THREAD

**Issue by DHowett** [theos/nic#1]
- `require target <target>`
- fragments
  - `require instance`
- makefile parsing (for `require target`, aggregation, and instancing)
- better error messages

**Comment by kirb** [comment]
Going to close considering the age (almost 10 years!), we’ve fared pretty well without these things and if we want to look into them again, I’d imagine it makes sense to re-evaluate completely and file new issues to ensure we’re meeting the needs of modern-day Theos projects.
